// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ProjectRH
{
    
    #region Windows Form Designer generated code
    public partial class MainWindow
    {
        private void InitializeComponent()
        {
            this.groupBoxFileInput = new System.Windows.Forms.GroupBox();
            this.pictureBoxBrowseIcon = new System.Windows.Forms.PictureBox();
            this.textBoxCurrentFile = new System.Windows.Forms.TextBox();
            this.tabControl = new System.Windows.Forms.TabControl();
            this.tabPageDetail = new System.Windows.Forms.TabPage();
            this.tabPageHex = new System.Windows.Forms.TabPage();
            this.textBoxHex = new System.Windows.Forms.TextBox();
            this.labelNameValue = new System.Windows.Forms.Label();
            this.panelInfoValues = new System.Windows.Forms.Panel();
            this.labelSizeValue = new System.Windows.Forms.Label();
            this.labelFormatValue = new System.Windows.Forms.Label();
            this.panelInfo = new System.Windows.Forms.Panel();
            this.panelInfoLabels = new System.Windows.Forms.Panel();
            this.labelFormat = new System.Windows.Forms.Label();
            this.labelSize = new System.Windows.Forms.Label();
            this.labelName = new System.Windows.Forms.Label();
            this.groupBoxFileInput.SuspendLayout();
            this.tabControl.SuspendLayout();
            this.tabPageDetail.SuspendLayout();
            this.tabPageHex.SuspendLayout();
            this.panelInfoValues.SuspendLayout();
            this.panelInfo.SuspendLayout();
            this.panelInfoLabels.SuspendLayout();
            // 
            // groupBoxFileInput
            // 
            this.groupBoxFileInput.Controls.Add(this.pictureBoxBrowseIcon);
            this.groupBoxFileInput.Controls.Add(this.textBoxCurrentFile);
            this.groupBoxFileInput.Size = new System.Drawing.Size(325, 53);
            this.groupBoxFileInput.Name = "groupBoxFileInput";
            this.groupBoxFileInput.Location = new System.Drawing.Point(15, 13);
            this.groupBoxFileInput.Text = "NVRAM Dump";
            this.groupBoxFileInput.Anchor = ((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right);
            this.groupBoxFileInput.TabStop = false;
            this.groupBoxFileInput.TabIndex = 0;
            // 
            // pictureBoxBrowseIcon
            // 
            this.pictureBoxBrowseIcon.Name = "pictureBoxBrowseIcon";
            this.pictureBoxBrowseIcon.TabStop = false;
            this.pictureBoxBrowseIcon.Cursor = System.Windows.Forms.Cursors.Hand;
            this.pictureBoxBrowseIcon.Location = new System.Drawing.Point(294, 20);
            this.pictureBoxBrowseIcon.Image = Properties.Resources.folder_explore;
            this.pictureBoxBrowseIcon.TabIndex = 1;
            this.pictureBoxBrowseIcon.Anchor = (System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right);
            this.pictureBoxBrowseIcon.Size = new System.Drawing.Size(24, 24);
            this.pictureBoxBrowseIcon.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBoxBrowseIcon.Click += new System.EventHandler(this.pictureBox1_Click);
            // 
            // textBoxCurrentFile
            // 
            this.textBoxCurrentFile.Name = "textBoxCurrentFile";
            this.textBoxCurrentFile.ForeColor = System.Drawing.SystemColors.WindowText;
            this.textBoxCurrentFile.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxCurrentFile.Location = new System.Drawing.Point(8, 20);
            this.textBoxCurrentFile.TabIndex = 0;
            this.textBoxCurrentFile.Anchor = ((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right);
            this.textBoxCurrentFile.Size = new System.Drawing.Size(278, 24);
            this.textBoxCurrentFile.BackColor = System.Drawing.SystemColors.Window;
            // 
            // tabControl
            // 
            this.tabControl.Name = "tabControl";
            this.tabControl.SelectedIndex = 0;
            this.tabControl.Anchor = ((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right);
            this.tabControl.Location = new System.Drawing.Point(15, 72);
            this.tabControl.TabIndex = 2;
            this.tabControl.Controls.Add(this.tabPageDetail);
            this.tabControl.Controls.Add(this.tabPageHex);
            this.tabControl.Size = new System.Drawing.Size(325, 306);
            this.tabControl.ItemSize = new System.Drawing.Size(54, 19);
            // 
            // tabPageDetail
            // 
            this.tabPageDetail.Name = "tabPageDetail";
            this.tabPageDetail.MaximumSize = new System.Drawing.Size(0, 0);
            this.tabPageDetail.Location = new System.Drawing.Point(4, 20);
            this.tabPageDetail.TabIndex = 0;
            this.tabPageDetail.Controls.Add(this.panelInfo);
            this.tabPageDetail.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageDetail.Size = new System.Drawing.Size(318, 282);
            this.tabPageDetail.BackColor = System.Drawing.Color.Transparent;
            //this.tabPageDetail.ImageKey = null;
            this.tabPageDetail.Text = "Detail";
            // 
            // tabPageHex
            // 
            this.tabPageHex.Name = "tabPageHex";
            this.tabPageHex.MaximumSize = new System.Drawing.Size(0, 0);
            this.tabPageHex.Location = new System.Drawing.Point(4, 20);
            this.tabPageHex.TabIndex = 1;
            this.tabPageHex.Controls.Add(this.textBoxHex);
            this.tabPageHex.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageHex.Size = new System.Drawing.Size(318, 282);
            //this.tabPageHex.ImageKey = null;
            this.tabPageHex.Text = "Hex";
            this.tabPageHex.UseVisualStyleBackColor = true;
            // 
            // textBoxHex
            // 
            this.textBoxHex.Name = "textBoxHex";
            this.textBoxHex.ForeColor = System.Drawing.SystemColors.WindowText;
            this.textBoxHex.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.textBoxHex.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxHex.Location = new System.Drawing.Point(3, 3);
            this.textBoxHex.TabIndex = 2;
            this.textBoxHex.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBoxHex.Size = new System.Drawing.Size(312, 25);
            this.textBoxHex.Font = new System.Drawing.Font("Courier New", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.textBoxHex.ReadOnly = true;
            this.textBoxHex.Multiline = true;
            // 
            // labelNameValue
            // 
            this.labelNameValue.Name = "labelNameValue";
            this.labelNameValue.Image = null;
            this.labelNameValue.TabIndex = 0;
            this.labelNameValue.Dock = System.Windows.Forms.DockStyle.Top;
            this.labelNameValue.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.labelNameValue.Size = new System.Drawing.Size(145, 23);
            this.labelNameValue.BackColor = System.Drawing.Color.Transparent;
            this.labelNameValue.Text = "labelNameValue";
            // 
            // panelInfoValues
            // 
            this.panelInfoValues.Name = "panelInfoValues";
            this.panelInfoValues.Location = new System.Drawing.Point(70, 0);
            this.panelInfoValues.TabIndex = 1;
            this.panelInfoValues.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelInfoValues.Controls.Add(this.labelFormatValue);
            this.panelInfoValues.Controls.Add(this.labelSizeValue);
            this.panelInfoValues.Controls.Add(this.labelNameValue);
            this.panelInfoValues.Size = new System.Drawing.Size(145, 69);
            this.panelInfoValues.BackColor = System.Drawing.Color.Transparent;
            // 
            // labelSizeValue
            // 
            this.labelSizeValue.Name = "labelSizeValue";
            this.labelSizeValue.Location = new System.Drawing.Point(0, 23);
            this.labelSizeValue.Image = null;
            this.labelSizeValue.TabIndex = 1;
            this.labelSizeValue.Dock = System.Windows.Forms.DockStyle.Top;
            this.labelSizeValue.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.labelSizeValue.Size = new System.Drawing.Size(145, 23);
            this.labelSizeValue.BackColor = System.Drawing.Color.Transparent;
            this.labelSizeValue.Text = "labelSizeValue";
            // 
            // labelFormatValue
            // 
            this.labelFormatValue.Name = "labelFormatValue";
            this.labelFormatValue.Location = new System.Drawing.Point(0, 46);
            this.labelFormatValue.Image = null;
            this.labelFormatValue.TabIndex = 2;
            this.labelFormatValue.Dock = System.Windows.Forms.DockStyle.Top;
            this.labelFormatValue.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.labelFormatValue.Size = new System.Drawing.Size(145, 23);
            this.labelFormatValue.BackColor = System.Drawing.Color.Transparent;
            this.labelFormatValue.Text = "labelFormatValue";
            // 
            // panelInfo
            // 
            this.panelInfo.Name = "panelInfo";
            this.panelInfo.Location = new System.Drawing.Point(7, 6);
            this.panelInfo.TabIndex = 2;
            this.panelInfo.Controls.Add(this.panelInfoValues);
            this.panelInfo.Controls.Add(this.panelInfoLabels);
            this.panelInfo.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panelInfo.Size = new System.Drawing.Size(217, 71);
            this.panelInfo.BackColor = System.Drawing.Color.Transparent;
            // 
            // panelInfoLabels
            // 
            this.panelInfoLabels.Name = "panelInfoLabels";
            this.panelInfoLabels.TabIndex = 3;
            this.panelInfoLabels.Dock = System.Windows.Forms.DockStyle.Left;
            this.panelInfoLabels.Controls.Add(this.labelFormat);
            this.panelInfoLabels.Controls.Add(this.labelSize);
            this.panelInfoLabels.Controls.Add(this.labelName);
            this.panelInfoLabels.Size = new System.Drawing.Size(70, 69);
            this.panelInfoLabels.BackColor = System.Drawing.Color.Transparent;
			this.panelInfoLabels.Padding = new System.Windows.Forms.Padding(0,0,10,0);
            // 
            // labelFormat
            // 
            this.labelFormat.Name = "labelFormat";
            this.labelFormat.Location = new System.Drawing.Point(0, 46);
            this.labelFormat.Image = null;
            this.labelFormat.TabIndex = 2;
            this.labelFormat.Dock = System.Windows.Forms.DockStyle.Top;
            this.labelFormat.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.labelFormat.Size = new System.Drawing.Size(70, 23);
            this.labelFormat.BackColor = System.Drawing.Color.Transparent;
            this.labelFormat.Text = "Format:";
            // 
            // labelSize
            // 
            this.labelSize.Name = "labelSize";
            this.labelSize.Location = new System.Drawing.Point(0, 23);
            this.labelSize.Image = null;
            this.labelSize.TabIndex = 1;
            this.labelSize.Dock = System.Windows.Forms.DockStyle.Top;
            this.labelSize.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.labelSize.Size = new System.Drawing.Size(70, 23);
            this.labelSize.BackColor = System.Drawing.Color.Transparent;
            this.labelSize.Text = "Size:";
            // 
            // labelName
            // 
            this.labelName.Name = "labelName";
            this.labelName.Image = null;
            this.labelName.TabIndex = 0;
            this.labelName.Dock = System.Windows.Forms.DockStyle.Top;
            this.labelName.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.labelName.Size = new System.Drawing.Size(70, 23);
            this.labelName.BackColor = System.Drawing.Color.Transparent;
            this.labelName.Text = "Name:";
            // 
            // MainWindow
            // 
            this.Name = "MainWindow";
            this.ClientSize = new System.Drawing.Size(355, 431);
            this.Controls.Add(this.tabControl);
            this.Controls.Add(this.groupBoxFileInput);
            this.Text = "ProjectRH";
            this.groupBoxFileInput.ResumeLayout(false);
            this.tabControl.ResumeLayout(false);
            this.tabPageDetail.ResumeLayout(false);
            this.tabPageHex.ResumeLayout(false);
            this.panelInfoValues.ResumeLayout(false);
            this.panelInfo.ResumeLayout(false);
            this.panelInfoLabels.ResumeLayout(false);
        }
        private System.Windows.Forms.GroupBox groupBoxFileInput;
        private System.Windows.Forms.PictureBox pictureBoxBrowseIcon;
        private System.Windows.Forms.TextBox textBoxCurrentFile;
        private System.Windows.Forms.TabControl tabControl;
        private System.Windows.Forms.TabPage tabPageDetail;
        private System.Windows.Forms.TabPage tabPageHex;
        private System.Windows.Forms.TextBox textBoxHex;
        private System.Windows.Forms.Label labelNameValue;
        private System.Windows.Forms.Panel panelInfoValues;
        private System.Windows.Forms.Label labelSizeValue;
        private System.Windows.Forms.Label labelFormatValue;
        private System.Windows.Forms.Panel panelInfo;
        private System.Windows.Forms.Panel panelInfoLabels;
        private System.Windows.Forms.Label labelFormat;
        private System.Windows.Forms.Label labelSize;
        private System.Windows.Forms.Label labelName;
    }
    #endregion
}
